version: '3'
services:
  frontend:
    image: appsec_frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
  backend:
    image: appsec_backend:latest
    ports:
      - "3500:3500"
    depends_on:
      - mongo
    env_file:
      - .env
  mongo:
    image: mongo:latest